#  May 6, 2020
#
# Animal Crossing: New Horizons is a 2020 life simulation video game developed and published by Nintendo for the Nintendo
# Switch. It is the fifth main series title in the Animal Crossing series. New Horizons was released in all regions on 
# March 20, 2020.
#
# The script takes sample fraction of user review text from those who rated the game "0" (very bad) and "10" (Very good).
# The text is then cleaned (ex. punctuation removed, a comment broken into sentences and tokens, replaced numbers with word 
# representation, removed special symbols, remove stop words and white spaces.) The resulting "unigram" data is tallied. I
# have selected four sentiments (joy, disgust, negative, positive) and mapped the 'nrc' sentiment lexicon from 'tidytext'
# for the NLP. The visualization is then generated by layering the plots.
#
#

#
# load ibrary
library(tidyverse)
library(tidytext)
library(grid)
library(png)


# Get the data
user_reviews <- readr::read_tsv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-05/user_reviews.tsv')

# comparison cloud image read back
img <- readPNG("/Users/abiyugiday/Documents/newProjects/tidytuesday/animal_crossing/fig/comparison_cloud_1.png")

# cleaned tokenized words from user review
df_unigram <- read.csv("~/Documents/newProjects/tidytuesday/animal_crossing/data/df_unigram.csv")

# 


# Prepare the raw user review data for the bar plot
df_rating <-
        user_reviews %>%
        group_by(grade) %>%
        tally(sort = TRUE) %>%
        mutate(prcnt = n/sum(n),
               grade = paste0("Rated_",grade)) %>%
        rename(num_students = n) %>%
        mutate(grade = forcats::fct_reorder(grade, prcnt, .desc= TRUE))


# nrc sentiment lexicon mapping 

nrc <- get_sentiments("nrc")
nrc_2 <- nrc %>% 
        filter(sentiment %in% c("joy", "disgust", "negative", "positive"))

# build comparison 
df_unigram %>% 
        select(word = 1, num = 2) %>% 
        inner_join(nrc_2) %>% 
        filter(!word %in% c("console", "player", "completely")) %>%
        acast(word ~ sentiment, value.var = "num", fill = 0) %>% 
        comparison.cloud(title.size = 3, 
                         match.colors = TRUE,
                         colors = c("indianred3", "chartreuse4", "rosybrown4", "orange3"), # color counter clock; start with right/top quadrant
                         #title.colors= "white", 
                         title.bg.colors = "seashell")


# set parameters for the raster object
df_img <- grid::rasterGrob(img, interpolate=TRUE, 
                           x = unit(0.6, "npc"), # position 
                           y = unit(0.4, "npc"), # position
                           width =  .5,          #width of img
                           height = .6,          #height of img
                           just = "centre" )


# Build the grphic plot
gg <- 
        ggplot(df_rating, aes(x = reorder(factor(grade),num_students), y = prcnt)) + 
        geom_bar(stat = "identity", color="gray30", fill = "seashell4") + 
        geom_bar(data = (df_rating %>% filter(grade %in% c("Rated_0", "Rated_10"))),
                 aes(x = reorder(factor(grade),num_students), y = prcnt), 
                 stat = "identity", color="black", fill = "lightslategray") + 
        scale_y_continuous(labels = scales::percent_format(), 
                           breaks= seq(0,.4,.05),
                           expand = c(0, 0.001)) +
        geom_text(aes(label = scales::percent(round(prcnt,2))), #scales::comma(num_students)), 
                  position = position_dodge(0.9), 
                  hjust = 1, #-.5,
                  colour = "white",
                  size = 4,
                  fontface = "bold") +
        coord_flip() 



gg <- gg + labs(x ="", 
                y ="",
                title = "Animal Crossing User Review Sentiment Analysis (NLP) ",
                subtitle = "A fraction of sampled user review comments from those who rated the game 0 (worst) & 10 (best). The 'nrc' sentiment lexicon is applied.",
                caption = "Source: https://villagerdb.com  | graphics: @abiyugiday") 

gg <- gg +  theme_abiyu() +
        theme(panel.grid.minor = element_blank(),
              panel.grid.major.y = element_blank(),
              plot.title    = element_text(size = 26, colour = "gray28", family = "Batang"),
              plot.subtitle  = element_text(size = 12, colour = "gray48"),
              plot.caption  = element_text(size =  12, colour = "gray48")
        )



gg <- gg +  annotation_custom(grob = df_img) 

gg